#!/usr/bin/env python3
"""mkgfx.py ASSETS OUTDIR -- the NES client's font and sprites, as ca65 source.

Reads ASSETS/font4x8.txt and ASSETS/sprites.txt and writes:

  OUTDIR/font.s   segment FONT: twelve 128-byte tables, _font_l1.._font_l6
                  and _font_r1.._font_r6. _font_lN[c] is row N of glyph c in
                  the left half of a byte (bits 7-4), _font_rN[c] the same
                  row in the right half (bits 3-0), so the blitter builds a
                  tile row -- two characters -- as one ORA of two lookups.
                  Rows 0 and 7 are not stored: they are blank in every glyph
                  and the blitter never writes them (src/nes/blit.s). The
                  segment is page-aligned in the linker config, so no lookup
                  ever pays a page-crossing cycle.
  OUTDIR/art.s    segment ART: the sprites' CHR, 32 bytes (two tiles) each,
                  in file order, for src/nes/sprites.c to copy into CHR-RAM
                  at $1000.
  OUTDIR/art.h    SPR_<NAME> for each sprite: its OAM tile number (the pair's
                  odd number, which selects the $1000 table in 8 x 16 mode),
                  and SPR_CHR_SIZE.

Both outputs are deterministic, so a rebuild with unchanged art leaves them
byte-identical and make sees nothing to do.
"""
import os
import re
import sys


def die(msg):
    print("mkgfx.py: " + msg, file=sys.stderr)
    sys.exit(1)


def blocks(path):
    """Yield (header words, [rows]) for each @ block, comments dropped.

    A comment is "#" alone or "# " and anything: a glyph row may itself start
    with '#', but never with a space after it."""
    head, rows = None, []
    for n, line in enumerate(open(path), 1):
        line = line.rstrip("\n")
        if line == "#" or line.startswith("# "):
            continue
        if line.startswith("@"):
            if head:
                yield head, rows
            head, rows = (line[1:].split(), n), []
            continue
        if not line.strip():
            continue
        if head is None:
            die("%s:%d: art before the first @" % (path, n))
        rows.append(line.strip())
    if head:
        yield head, rows


# ---- the font --------------------------------------------------------------

def font(path):
    glyph = {}
    for (words, n), rows in blocks(path):
        code = int(words[0])
        if not 0 < code < 128:
            die("%s:%d: code %d is not 1-127" % (path, n, code))
        if len(rows) != 8 or any(len(r) != 4 or set(r) - set(".#") for r in rows):
            die("%s:%d: glyph %d is not 8 rows of 4 '.'/'#'" % (path, n, code))
        if "#" in rows[0] or "#" in rows[7]:
            die("%s:%d: glyph %d draws in row 0 or row 7" % (path, n, code))
        glyph[code] = [int(r.replace("#", "1").replace(".", "0"), 2) for r in rows]
    blank = [0] * 8
    lines = ["; font.s -- generated by tools/nes/mkgfx.py from assets/nes/font4x8.txt",
             "; Do not edit.", "",
             "        .segment \"FONT\"", ""]
    for half, shift in (("l", 4), ("r", 0)):
        for row in range(1, 7):
            name = "_font_%s%d" % (half, row)
            data = []
            for c in range(128):
                data.append(glyph.get(c, blank)[row] << shift)
            lines.append("        .export %s" % name)
            lines.append("%s:" % name)
            for i in range(0, 128, 16):
                lines.append("        .byte   " +
                             ",".join("$%02X" % b for b in data[i:i + 16]))
            lines.append("")
    return "\n".join(lines) + "\n"


# ---- the sprites -------------------------------------------------------------

def sprites(path):
    sprites = []                        # (name, 16 rows of 8 chars)
    for (words, n), rows in blocks(path):
        name = words[0]
        width = int(words[1]) if len(words) > 1 and words[1].isdigit() else 8
        scale = 2 if "x2" in words else 1
        if len(rows) != 16 or any(len(r) != width or set(r) - set(".123") for r in rows):
            die("%s:%d: %s is not 16 rows of %d" % (path, n, name, width))
        if scale == 2:
            rows = [r.replace(".", "..").replace("1", "11").replace("2", "22")
                     .replace("3", "33") for r in rows for _ in (0, 1)]
            name = name + "_big"
            width *= 2
        cols = width // 8
        bands = len(rows) // 16
        if width % 8:
            die("%s:%d: %s is not a whole number of sprites wide" % (path, n, name))
        k = 0
        for band in range(bands):
            for col in range(cols):
                part = [r[col * 8:col * 8 + 8] for r in rows[band * 16:band * 16 + 16]]
                sname = name if cols * bands == 1 else "%s_%d" % (name, k)
                sprites.append((sname, part))
                k += 1
    chr_ = bytearray()
    for name, part in sprites:
        for tile in (part[:8], part[8:]):
            p0 = [int("".join("1" if ch in "13" else "0" for ch in r), 2) for r in tile]
            p1 = [int("".join("1" if ch in "23" else "0" for ch in r), 2) for r in tile]
            chr_ += bytes(p0) + bytes(p1)
    if len(chr_) > 3 * 1024:
        die("the sprites need %d bytes of CHR; 3K are set aside" % len(chr_))
    s = ["; art.s -- generated by tools/nes/mkgfx.py from assets/nes/sprites.txt",
         "; Do not edit.", "",
         "        .segment \"ART\"",
         "        .export _spr_chr", "_spr_chr:"]
    for i in range(0, len(chr_), 16):
        s.append("        .byte   " + ",".join("$%02X" % b for b in chr_[i:i + 16]))
    h = ["/* art.h -- generated by tools/nes/mkgfx.py from assets/nes/sprites.txt.",
         "   Do not edit. */", "#ifndef GEN_NES_ART_H", "#define GEN_NES_ART_H", ""]
    for i, (name, _) in enumerate(sprites):
        h.append("#define SPR_%-14s 0x%02X" % (re.sub(r"\W", "_", name).upper(), i * 2 + 1))
    h += ["", "#define SPR_CHR_SIZE    %d" % len(chr_),
          "extern const unsigned char spr_chr[SPR_CHR_SIZE];", "", "#endif"]
    return "\n".join(s) + "\n", "\n".join(h) + "\n"


def write(path, text):
    try:
        if open(path).read() == text:
            return
    except OSError:
        pass
    open(path, "w").write(text)


def main():
    if len(sys.argv) != 3:
        print(__doc__.strip(), file=sys.stderr)
        return 2
    assets, out = sys.argv[1:]
    os.makedirs(out, exist_ok=True)
    write(os.path.join(out, "font.s"), font(os.path.join(assets, "font4x8.txt")))
    art_s, art_h = sprites(os.path.join(assets, "sprites.txt"))
    write(os.path.join(out, "art.s"), art_s)
    write(os.path.join(out, "art.h"), art_h)
    return 0


if __name__ == "__main__":
    sys.exit(main())
